"""Read-only discovery of exact poses generated by ArcticSim."""

from __future__ import annotations

import json
import urllib.request
from dataclasses import dataclass
from typing import Any

from .tower import TowerWorldPose


@dataclass(frozen=True, slots=True)
class GeneratedAssetPose:
    name: str
    asset_type: str
    latitude: float
    longitude: float
    world_x_m: float
    world_y_m: float
    ground_world_z_m: float
    model_world_z_m: float
    yaw_rad: float
    camera_world_z_m: float | None = None

    def as_tower(self) -> TowerWorldPose:
        if self.asset_type != "tower" or self.camera_world_z_m is None:
            raise ValueError(f"asset {self.name!r} has no generated tower camera pose")
        return TowerWorldPose(
            self.name,
            self.latitude,
            self.longitude,
            self.camera_world_z_m,
        )


class ArcticSimMetadataClient:
    """Fetch generated asset metadata without changing simulator state."""

    def __init__(
        self,
        host: str,
        *,
        port: int = 8090,
        timeout_s: float = 5.0,
        opener: Any = urllib.request.urlopen,
    ) -> None:
        self.url = f"http://{host}:{port}/api/assets"
        self.timeout_s = timeout_s
        self._opener = opener

    def fetch(self) -> tuple[GeneratedAssetPose, ...]:
        with self._opener(self.url, timeout=self.timeout_s) as response:
            payload = json.load(response)
        if not payload.get("ok"):
            raise RuntimeError("ArcticSim asset metadata is unavailable")
        generated = []
        for asset in payload.get("assets", []):
            pose = asset.get("pose")
            if not asset.get("rostered") or not isinstance(pose, dict):
                continue
            generated.append(
                GeneratedAssetPose(
                    name=str(pose["name"]),
                    asset_type=str(pose["type"]),
                    latitude=float(pose["latitude"]),
                    longitude=float(pose["longitude"]),
                    world_x_m=float(pose["world_x_m"]),
                    world_y_m=float(pose["world_y_m"]),
                    ground_world_z_m=float(pose["ground_world_z_m"]),
                    model_world_z_m=float(pose["model_world_z_m"]),
                    yaw_rad=float(pose["yaw_rad"]),
                    camera_world_z_m=(
                        float(pose["camera_world_z_m"])
                        if pose.get("camera_world_z_m") is not None
                        else None
                    ),
                )
            )
        return tuple(generated)

    def towers(self) -> tuple[TowerWorldPose, ...]:
        return tuple(
            asset.as_tower()
            for asset in self.fetch()
            if asset.asset_type == "tower"
        )
